name: deploy

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::853955636908:role/oidc_role
          aws-region: eu-central-1
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.6"

      - run: terraform init
      - run: terraform plan
      - run: terraform apply -auto-approve
          